name: Docker Nightly Production

on:
  push:
    branches:
      - workflow
    paths-ignore:
      - '*.md'
      - '.devcontainer/**'
      # I'm not excluding .github as changes in there might be to workflows etc
      - '.vscode/**'
      - 'docs/**'

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yml

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: ./.github/workflows/partial-frontend.yml

  build-release:
    permissions:
      contents: read
      packages: write
      # The id-token write permission is needed to connect to Depot.dev
      # as part of the partial-builder.yml action. It needs to be declared
      # in the parent action, as noted here:
      # https://github.com/orgs/community/discussions/76409#discussioncomment-8131390
      id-token: write
    name: Build Tagged Release
    if: github.repository == 'mealie-recipes/mealie'
    uses: ./.github/workflows/partial-builder.yml
    needs:
      - frontend-tests
      - backend-tests
    with:
      tag: nightly
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

