name: Docker Build Production

on:
  release:
    types: [published]

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yml

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: ./.github/workflows/partial-frontend.yml

  build-release:
    permissions:
      contents: read
      packages: write
      id-token: write  # Permission pour se connecter à un registre privé si nécessaire
    name: Build Tagged Release
    uses: ./.github/workflows/partial-builder.yml
    needs:
      - backend-tests
      - frontend-tests
    with:
      tag: ${{ github.event.release.tag_name }}
      tags: |
        hkotel/mealie:latest
        ghcr.io/${{ github.repository }}:latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
